### PR TITLE
retain the barest shred of human decency

### PR DESCRIPTION
**Pull request by durantjm198**
you still have time

### CODE REVIEW

**Comment by bippum** [comment]
This presents an ethical dilemma. Are you saying said entries in words.txt are not words

**Comment by bippum** [comment]
(Also I have no idea how to push my changes to Google App Engine anymore so)

**Comment by no-boot-device** [comment]
haha good job

**Comment by odoglv1** [comment]
nice job!!

**Comment by odoglv1** [comment]
[https://help.twitter.com/forms/general](https://help.twitter.com/forms/general) get the bot unsuspended?

**Comment by bippum** [comment]
God bless america

**Comment by atribecalledkwest** [comment]
This was by far the easiest "Okay yeah I'll accept that PR" I've seen in the past year. Congrats.

**Comment by bippum** [comment]
@atribecalledkwest like i said i can't push to google app engine anymore, the word list there is uncontrollable unless i delete the app (which i have done now that it's no longer needed)

**Comment by kroogs** [comment]
Why pretend that's the reason you dragged your feet when we can all clearly see it wasn't the most important to you? Your disingenuousness is transparent.

**Comment by bippum** [comment]
Why do you care so much about a joke internet bot lol

**Pull request closed without merging**
